import "./css/shared-style.css";
import "./css/middle-section/main-middle-style.css";
import "./css/main-right-style.css";
import "./css/left-section/main-left-style.css";
import "./css/left-section/add-project-btn.css";
import "./css/left-section/home-container.css";
import "./css/left-section/project-container.css";
import "./css/left-section/project-edit-box.css";
import "./css/left-section/project-create-rename-form.css";
import "./css/middle-section/middle-header.css";
import "./css/middle-section/middle-sorting-box.css";
import "./css/middle-section/middle-todo-list.css";
import "./css/middle-section/middle-add-todo-btn.css";
import "./css/header-style.css";
import html from "./admin.html";
